---
name: Update antora.yml
description: Github Action to adjust version information in antora.yml depending on current branch or version tag.
inputs:
  ref: # id of input
    description: Github Ref
    required: true
runs:
  using: 'docker'
  image: 'src/main/Dockerfile'
  args:
    - ${{ inputs.ref }}
